version: '3.6'

services:
  app:
    image: chialab/php:7.2-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:80

  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db_default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3000:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: example